\." Manpage for issc
\." Author of the nssltof package : sendai <c> 2013.
.TH issc 1 "05 Jun 2013" "SunOS 5.10" "NSSLTOF package"
.SH NAME
issc - NSS2 compatible nsswitch backend for NSSLTOF package
.SH SYNOPSIS
.LP
.sp
/etc/nsswitch.conf:

passwd: files issc
.br
group:  files issc

.SH DESCRIPTION
issc is a simple NSS2 compatible nsswitch backend which does exactly the same as 'files' except
that instead of using the original backend files :
.sp
.br
/etc/passwd
.br
/etc/shadow
.br
/etc/group
.br
.sp
will use :
.sp
.br
/etc/passwd.cache
.br
/etc/shadow.cache
.br
/etc/group.cache
.br
.sp
These files should be updated using nssltofd(1M), the daemon which is also part of the NSSLTOF package. The cache files 
use the exact same format as the original 'files' files format.

.SH SEE ALSO
nssltofd(1M)
.SH FILES 
/etc/nsswitch.conf
.br
/usr/lib/nss_issc.so.1
.br
/usr/lib/libnss_files.so (symlink to /lib/nss_files.so.1)
.br